// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab7;

namespace lab7.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200330154638_Make Student UpdatedAt Nullable")]
    partial class MakeStudentUpdatedAtNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab7.Group", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(10)")
                    .HasMaxLength(10);

                b.HasKey("Id");

                b.ToTable("Groups");
            });

            modelBuilder.Entity("lab7.Student", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("FirstName")
                    .HasColumnType("nvarchar(30)")
                    .HasMaxLength(30);

                b.Property<int>("GroupId")
                    .HasColumnType("int");

                b.Property<string>("LastName")
                    .HasColumnType("nvarchar(30)")
                    .HasMaxLength(30);

                b.Property<DateTime?>("UpdatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValue(null);

                b.HasKey("Id");

                b.HasIndex("GroupId");

                b.ToTable("Students");
            });

            modelBuilder.Entity("lab7.Student", b =>
            {
                b.HasOne("lab7.Group", "Group")
                    .WithMany("Students")
                    .HasForeignKey("GroupId")
                    .HasConstraintName("FK_Group_Students")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}